### ISSUE TITLE
Clarity on list-enabled/disabled

### ISSUE THREAD

**Issue by Pete-Hamlin** [0xl3vi/hostsctl#14]
I'm currently a little puzzled on the whole setup with the 3 seperate host files in hostctl.d in relation to the 'list-***' functions. I currently see it as the following:

10-hosts doesn't actually do anything unless you manual add to it using a text editor
20-enabled-disabled contains user defined hosts added using the 'enable/disable' command that aren't already included in the remote file
30-remote contains all remote hosts

I can see a justifiable argument as to why each of these should be included in a cascading cat & merge setup, going from 10 being top priority to 30 being bottom. However, what doesn't make sense to me is that the list-enabled/disabled is currently pointed at the 20-enabled-disabled list, meaning it will only list a very small number of disabled/enabled host files that aren't included in the remote hosts.

Surely it would make more sense to point the functions at /etc/hosts, so all hosts are effectivelt listed (i.e. change the `ENABLED_DISABLED_HOSTS` arg to `HOSTS` in the appropriate functions in the script)? Just clarifying, is this a deliberate design choice or otherwise?

Happy to make a pull request with the updated code if it's the latter, or close this one if it's the former, just wanted to double check.

Cheers for the script :)

**Comment by 0xl3vi** [comment]
Please follow #6 to review the changes.
`10-hosts` is the original /etc/hosts file.
