### ISSUE TITLE
Where is URL variable?!

### ISSUE THREAD

**Issue by mbnoimi** [0xl3vi/hostsctl#16]
Hi, 

> Before you can start using hostsctl you need to select hosts file.
.
.
> Place the hosts file url in the URL variable in hostsctl.sh

Where can I find ```URL``` variable? I opened [hostsctl.sh](https://raw.githubusercontent.com/0xl3vi/hostsctl/master/bin/hostsctl.sh) but I couldn't find the variable?!

Ex. I want to use https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt

**Comment by 0xl3vi** [comment]
The `URL` variable has been replaced with `remote_hosts`
the new README.md will be updated soon by @pigmonkey
