### ISSUE TITLE
System Compatibility

### ISSUE THREAD

**Issue by MountainMan22** [0xl3vi/hostsctl#22]
Will this work with mac or any other system besides arch ?

**Comment by 0xl3vi** [comment]
Hi @MountainMan22 `hostsctl` will work on any linux, BSD (with bash installed).
I dont own Mac, so I cant tell you if it will work.

Do you have mac?

**Comment by MountainMan22** [comment]
yes

**Comment by 0xl3vi** [comment]
@MountainMan22 OK, and It's working/not working for you?

1. `install.sh` failed?
please describe what is the errors?
or post a screenshot of your terminal.

**Comment by MountainMan22** [comment]
The system integrity protection wont allow the install.sh to write to /bin directory. So any updating always fails.

**Comment by MountainMan22** [comment]
The system integrity protection doesn't allow files to be written in the /usr/bin directory. Changing the PREFIX="/usr" to PREFIX="/usr/local"will work. Even running with sudo root doesn't have the permissions to write in the "/usr" directory. This is specifically for macOS.

**Comment by 0xl3vi** [comment]
@MountainMan22 OK, I think you right I will change `PREFIX` to "/usr/local/"
thank for the report :+1:

**Comment by MountainMan22** [comment]
@0xl3vi Everything installed properly by changing the PREFIX to "/usr/local/" . Thanks for the awesome project and keep up the good work.
