### ISSUE TITLE
How to reset hostsctl?

### ISSUE THREAD

**Issue by mbnoimi** [0xl3vi/hostsctl#26]
Hi,

How can I reset hostsctl to its default configurations?

Ex. I enabled some domains but when I called ```list-enabled``` I found 181 entries while I only enabled some domains!

**Comment by mbnoimi** [comment]
BTW, I tried to call ```hostsctl restore``` but unfortunately it didn't restore the default hosts!

**Comment by 0xl3vi** [comment]
`hostsctl restore` will restore your original /etc/hosts.

try:
```
sudo hostsctl update
```

this will update remote hosts and merge all.

**Comment by mbnoimi** [comment]
@0xl3vi thanks.

> hostsctl restore will restore your original /etc/hosts.

I did. ```/etc/hosts``` still contains ```hostsctl``` not the original file!

**Comment by 0xl3vi** [comment]
@mbnoimi this is due the bug in `install.sh`.

**Comment by pigmonkey** [comment]
> I enabled some domains but when I called list-enabled I found 181 entries while I only enabled some domains!

This is related to #4. We currently consider any host entry starting with a `#` to be "enabled" (including those commented out by default in your remote hosts file) even if there is an uncommented entry for the same host somewhere else in the file.

**Comment by mbnoimi** [comment]
> This is related to #4

OMG, How can restore the original hosts file?!

**Comment by mbnoimi** [comment]
I decided to uninstall hostsctl because it broke my machine. I'll wait until releasing a stable version.

See more #25
