### ISSUE TITLE
New default hosts file.

### ISSUE THREAD

**Issue by 0xl3vi** [0xl3vi/hostsctl#27]
RIght now, we are using Steven Black [Hosts](https://github.com/StevenBlack/hosts/blob/master/readme.md) file.
but I think we should create a script to generate the file instead of using external.

or better, a "smart" hosts file, i.e: 
/etc/hostsctl.d/hosts:
```awk

Include "http://url/hosts1.txt"
Include "http://url/hosts2.txt"

Allow "twitter.com"
Allow "google.com"
Disable "*.facebook"
Disable "cnn.com"
Disable "xxx.xxx"
```

In this way we can `Include` multiple files in once.
and `hostsctl` will download the files to `30-remote`.
we can use this as a `hostsctl.conf` file and not "a smat hosts file"

I will also add `hosts_secure` function to ensure all hosts has the IP address `0.0.0.0`.
just in case the remote hosts file is malicious.

.

**Comment by pigmonkey** [comment]
The main appeal of hostsctl for me is that it provides a convenient way to utilize external, well-maintained host files like Steven Black project, while also letting me handle the few exceptions I want to make. I wouldn't want to loose that ability.

Allowing multiple remote URLs seems fine to me, whether that's done in the syntax you suggest or just as a bash array in the existing config.

I'm not sure how disabling via regex would work. `/etc/hosts` doesn't support regex, as far as I know, so the only way to disable `*.facebook.com` would be to include an entry for all possible subdomains, right?

**Comment by 0xl3vi** [comment]
@pigmonkey we can use `awk` for regex.
but yeah you probably right.
